### PR TITLE
Vu-1075 allow parsing ts files

### PR DESCRIPTION
**Pull request by thomas-vurvey**
CI was already failing previously, misconfiguration.
How is it deployed?

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
CI is failing because the package-lock.json was deleted and the github actions yaml wasn't updated to use npm install instead of npm ci.

This is deployed to npm through the batterii group, which i think means if you have write access to the group, you can deploy.

The change you made shouldn't be necessary. When are you consuming un-transpiled typescript? How is `require` reading it correctly?

**Comment by thomas-vurvey** [comment]
> CI is failing because the package-lock.json was deleted and the github actions yaml wasn't updated to use npm install instead of npm ci.
> 
> This is deployed to npm through the batterii group, which i think means if you have write access to the group, you can deploy.
> 
> The change you made shouldn't be necessary. When are you consuming un-transpiled typescript? How is `require` reading it correctly?

Its being used in vurvey-api like this: 
https://github.com/Batterii/vurvey-api/pull/790#issuecomment-1618825123
Its using different ts loader

**Comment by NoahTheDuke** [comment]
I no longer work for Batterii so I can't see that merge request. I would recommend adding support for that loader directly to fixture riveter and testing it.

**Comment by thomas-vurvey** [comment]
> I no longer work for Batterii so I can't see that merge request. I would recommend adding support for that loader directly to fixture riveter and testing it.

Its too much hustle for now, just needs this simple feature. Ive removed altering previous fn and added a new one with doc

**Review by jroell — APPROVED** [review]

**Pull request merged**
